Install missing dep in builder docker image
This change fixes the following error during building in the docker
container:

    error: Failed build dependencies:
            libtool-ltdl-devel is needed by pbspro-19.0.0-0.x86_64
    The command '/bin/sh -c git clone https://github.com/pbspro/pbspro.git /src/pbspro &&     bash /src/pbspro/docker/centos7/build.sh' returned a non-zero code: 1